Merge from cs220-private + Update info on safe exam browser, ChatGPT
kaist-cp/cs220 pull request #242
Opened 2023-08-22 09:17 UTC by AnHaechan

2023-08-23 04:40 UTC, jeehoonkang requested changes

2023-08-23 04:40 UTC, jeehoonkang commented on assets/why3/assignment05/binary_search.mlw
> +end
newline

2023-08-24 15:50 UTC, jeehoonkang requested changes

2023-08-24 15:50 UTC, jeehoonkang commented on assets/why3/assignment05/binary_search.mlw
> +end
every file ends with a newline

2023-08-24 15:50 UTC, aqua-universalis commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2023-08-25T00:50:48
          
          
            * 메일 제목 : 
Re: [kaist-cp/cs220] Merge from cs220-private + Update info on safe exam browser, ChatGPT (PR #242)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2023-08-25 04:54 UTC, merged

2023-08-25 04:54 UTC, aqua-universalis commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2023-08-25T13:54:43
          
          
            * 메일 제목 : 
Re: [kaist-cp/cs220] Merge from cs220-private + Update info on safe exam browser, ChatGPT (PR #242)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.